/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package regexengine

import java.util.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

}






